-- Avdelinger:
DELETE FROM branches;
INSERT INTO branches (branchcode, branchname) VALUES
("dfb", "Det Flerspråklige Bibliotek"),
("dfbs", "Det Flerspråklige Bibliotek Referanse"),
("fbje", "Bjerke"),
("fbjh", "Bjerke, lokalhistorie"),
("fbji", "Bjerke, innvandrerlitteratur"),
("fbjl", "Bjørnholt læremidler"),
("fbjo", "Bjørnholt"),
("fbju", "Bjørnholt ungdomsskole"),
("fbli", "vet ikke"),
("fbol", "Bøler"),
("fdum", "dummy"),
("ffur", "Furuset"),
("fgam", "Gamle Oslo"),
("fgry", "Grünerløkka"),
("fgyi", "Grünerløkka innvanrerlitteratur"),
("fhol", "Holmlia"),
("flam", "Lambertseter"),
("fmaj", "Majorstua"),
("fnor", "Nordtvet"),
("fnti", "Fnatt!"),
("fnyd", "Nydalen"),
("fopp", "Oppsal"),
("frik", "Rikshospitalet"),
("frmm", "Rommen"),
("froa", "Røa"),
("from", "Romsås"),
("fsme", "Smestad"),
("fsor", "Sørkedalen nærbibliotek"),
("fsti", "Stovner innlån?"),
("fsto", "Stovner"),
("ftoi", "Torshov innvandrerlitteratur"),
("ftor", "Torshov"),
("fxxx", "filial X"),
("hbar", "Barneavdelingen (Hovedutlånet)"),
("hbbr", "Barneavdelingen spesialsamling"),
("hsko", "Skoleavdelingen"),
("hutl", "Hovedbiblioteket"),
("hvkr", "Katalogavdeling referanse"),
("hvlr", "Stjernesamling, lesesalen"),
("hvmu", "Musikkavdelingen (Hovedbiblioteket)"),
("hvur", "Spesialsamling, fjernlån"),
("idep", "depot?"),
("info", "til info?"),
("ukjent", "ukjent avdeling");

-- Autoriserte verdier for eksemplarstatuser:
DELETE FROM authorised_values WHERE category IN ("WITHDRAWN", "LOST", "NOT_LOAN", "RESTRICTED", "DAMAGED");
INSERT INTO authorised_values (category, authorised_value, lib) VALUES
("WITHDRAWN", "1", "trukket tilbake"),
("DAMAGED", "1", "skadet"),
("LOST", "1", "tapt"),
("LOST", "2", "regnes som tapt"),
("LOST", "3", "tapt og erstattet"),
("LOST", "4", "ikke på plass"),
("LOST", "5", "påstått levert"),
("LOST", "6", "påstått ikke lånt"),
("LOST", "7", "borte i transport"),
("LOST", "8", "tapt, regning betalt"),
("LOST", "9", "vidvanke, registrert forsvunnet"),
("LOST", "10", "retur eieravdeling (ved import"),
("LOST", "11", "til henteavdeling (ved import)"),
("NOT_LOAN", "-1", "i bestilling"),
("NOT_LOAN", "2", "ny"),
("NOT_LOAN", "3", "til internt bruk"),
("NOT_LOAN", "4", "til katalogisering"),
("NOT_LOAN", "5", "vurderes kassert"),
("NOT_LOAN", "6", "til retting"),
("NOT_LOAN", "7", "til innbinding"),
("RESTRICTED", "1", "begrenset tilgang"),
("RESTRICTED", "2", "referanseverk");

-- Lånerkategorier:
DELETE FROM categories;
INSERT INTO categories (categorycode, description) VALUES
("ADMIN", "administrator"),
("AUTO", "Automat"),
("B", "Barn"),
("B01", "B01"),
("B02", "B02"),
("B03", "B03"),
("B04", "B04"),
("B05", "B05"),
("B06", "B06"),
("B07", "B07"),
("B08", "B08"),
("B09", "B09"),
("B10", "B10"),
("B11", "B11"),
("B12", "B12"),
("B14", "B14"),
("B15", "B15"),
("B16", "B16"),
("B17", "B17"),
("B18", "B18"),
("B19", "B19"),
("B20", "B20"),
("B21", "B21"),
("BHG", "Barnehage"),
("BKM", "Boken kommer"),
("ELE", "Elevlåner"),
("EU", "EU"),
("F01", "F01"),
("F02", "F02"),
("F03", "F03"),
("F04", "F04"),
("F05", "F05"),
("F06", "F06"),
("F07", "F07"),
("F08", "F08"),
("F11", "F11"),
("F12", "F12"),
("F14", "F14"),
("F15", "F15"),
("F16", "F16"),
("F18", "F18"),
("F19", "F19"),
("F20", "F20"),
("F93", "F93"),
("F98", "F98"),
("FJL", "Fjernlån"),
("G01", "G01"),
("G02", "G02"),
("G03", "G03"),
("G04", "G04"),
("G05", "G05"),
("G06", "G06"),
("G07", "G07"),
("G08", "G08"),
("G09", "G09"),
("G10", "G10"),
("G11", "G11"),
("G12", "G12"),
("G14", "G14"),
("G15", "G15"),
("G16", "G16"),
("G17", "G17"),
("G18", "G18"),
("G19", "G19"),
("G20", "G20"),
("HB", "Hjemmelåner"),
("I", "Institusjon"),
("J", "Ungdom"),
("KL", "Grunnskole"),
("L", "Fylkes-/folkebibliotek"),
("MA", "Makslån voksen"),
("MDL", "Midlertidig bosatt"),
("MXV", "MXV"),
("NB", "NB"),
("NF", "NF"),
("OV", "OV"),
("PAS", "Pasient"),
("S", "Bibliotekansatt"),
("SKO", "Skole"),
("STL", "STL"),
("U", "Ukjent"),
("U01", "U01"),
("U02", "U02"),
("U03", "U03"),
("U04", "U04"),
("U05", "U05"),
("U06", "U06"),
("U07", "U07"),
("U08", "U08"),
("U09", "U09"),
("U10", "U10"),
("U11", "U11"),
("U12", "U12"),
("U14", "U14"),
("U15", "U15"),
("U16", "U16"),
("U17", "U17"),
("U18", "U18"),
("U19", "U19"),
("U20", "U20"),
("U21", "U21"),
("U23", "U23"),
("UE", "Utgått elev"),
("V", "Voksen"),
("V01", "V01"),
("V02", "V02"),
("V03", "V03"),
("V04", "V04"),
("V05", "V05"),
("V06", "V06"),
("V07", "V07"),
("V08", "V08"),
("V09", "V09"),
("V10", "V10"),
("V11", "V11"),
("V12", "V12"),
("V14", "V14"),
("V15", "V15"),
("V16", "V16"),
("V17", "V17"),
("V18", "V18"),
("V19", "V19"),
("V20", "V20"),
("V21", "V21"),
("VGS", "Videregående skole"),
("ZZZ", "ZZZ");